name: Maven Sonar Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Sonar analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze (Sonar)
        working-directory: backend/homework/5/hospital-staffing
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.verbose=true \
            -Dsonar.projectKey=${{ secrets.KDUER_NAME }}-BE-Homework-5 \
            -Dsonar.projectName=${{ secrets.KDUER_NAME }}-BE-Homework-5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: .github/actions-scripts/package-lock.json

      - name: Install dependencies
        working-directory: .github/actions-scripts/
        run: npm ci

      - name: Run script
        run: node .github/actions-scripts/post-comment.js
        env:
          PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.KDUER_NAME }}-BE-Homework-5
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          REPO_NAME_GITHUB: ${{ secrets.REPO_NAME_GITHUB }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          SQ_USERNAME: ${{ secrets.SQ_USERNAME }}
          SQ_KEY: ${{ secrets.SQ_KEY }}
